# code auto-generated by material_relations_generate.py
from simphony.material_relations.material_relation import (
    MaterialRelation)
from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation
from simphony.core.data_container import DataContainer


class Coulomb(MaterialRelation):

    """ A Coulomb material-relation

    Coulomb material relation

    Attributes
    ----------
    cutoff_distance : <type 'numpy.float64'>
        Cutoff Distance
    dielectric_constant : <type 'numpy.float64'>
        Dielectric Constant

    """

    def __init__(
        self,
        name,
        materials,
        description="",
        cutoff_distance=1.0,
        dielectric_constant=1.0
    ):
        super(Coulomb, self).__init__(
            name=name,
            description=description,
            kind=CUDSMaterialRelation.COULOMB,
            materials=materials,
            parameters=DataContainer({
                CUBA.CUTOFF_DISTANCE: cutoff_distance,
                CUBA.DIELECTRIC_CONSTANT: dielectric_constant,
            })
        )

    @property
    def cutoff_distance(self):
        return self._parameters[CUBA.CUTOFF_DISTANCE]

    @cutoff_distance.setter
    def cutoff_distance(self, value):
        updated_parameters = self._parameters
        updated_parameters[CUBA.CUTOFF_DISTANCE] = value
        self._parameters = updated_parameters

    @property
    def dielectric_constant(self):
        return self._parameters[CUBA.DIELECTRIC_CONSTANT]

    @dielectric_constant.setter
    def dielectric_constant(self, value):
        updated_parameters = self._parameters
        updated_parameters[CUBA.DIELECTRIC_CONSTANT] = value
        self._parameters = updated_parameters
