# auto-generated by the material_relations_generate.py script.
from enum import IntEnum, unique


@unique
class CUDSMaterialRelation(IntEnum):

    LENNARD_JONES = 1
    COULOMB = 2
    COULOMB_FRICTION_FORCE = 3
    DISSIPATION_FORCE = 4
    SJKR_COHESION_FORCE = 5
