# code auto-generated by the cuba-generate.py script.
from enum import IntEnum, unique


@unique
class CUDSItem(IntEnum):

    POINT = 0
    PARTICLE = 1
    BOND = 2
    EDGE = 3
    FACE = 4
    CELL = 5
    NODE = 6
