# code auto-generated by the material_relations_generate.py script.
from collections import namedtuple

from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation


ATTRIBUTES = [
 "number", "class_name", "allowed_number_materials",
 "doc_description", "supported_parameters"]
Material_Relation_Information = namedtuple("Material_Relation_Information",
                                           ATTRIBUTES)

Parameter = namedtuple("Parameter", ["cuba_key", "default_value"])


MATERIAL_RELATIONSHIP_INFORMATION = {
    CUDSMaterialRelation.LENNARD_JONES: Material_Relation_Information(
        class_name='LennardJones',
        number=1,
        allowed_number_materials=[1, 2],
        doc_description='Lennard Jones material relation',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.CUTOFF_DISTANCE,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.ENERGY_WELL_DEPTH,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.VAN_DER_WAALS_RADIUS,
                       default_value=1.0), ]
     ),
    CUDSMaterialRelation.COULOMB: Material_Relation_Information(
        class_name='Coulomb',
        number=2,
        allowed_number_materials=[1, 2],
        doc_description='Coulomb material relation',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.CUTOFF_DISTANCE,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.DIELECTRIC_CONSTANT,
                       default_value=1.0), ]
     ),
}
