# code auto-generated by the material_relations_generate.py script.
from collections import namedtuple

from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation


ATTRIBUTES = [
    "number", "class_name", "allowed_number_materials",
    "doc_description", "supported_parameters"]
Material_Relation_Definition = namedtuple("Material_Relation_Definition",
                                          ATTRIBUTES)

Parameter = namedtuple("Parameter", ["cuba_key", "default_value"])


MATERIAL_RELATION_DEFINITIONS = {
    CUDSMaterialRelation.LENNARD_JONES: Material_Relation_Definition(
        class_name='LennardJones',
        number=1,
        allowed_number_materials=[1, 2],
        doc_description='Approximated potential energy of interaction between a pair of neutral atoms or molecules based on their distance of separation.',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.CUTOFF_DISTANCE,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.ENERGY_WELL_DEPTH,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.VAN_DER_WAALS_RADIUS,
                       default_value=1.0), ]
     ),
    CUDSMaterialRelation.COULOMB: Material_Relation_Definition(
        class_name='Coulomb',
        number=2,
        allowed_number_materials=[1, 2],
        doc_description='Effective potential energy of the interaction between a pair of point charges.',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.CUTOFF_DISTANCE,
                       default_value=1.0),
             Parameter(cuba_key=CUBA.DIELECTRIC_CONSTANT,
                       default_value=1.0), ]
     ),
    CUDSMaterialRelation.COULOMB_FRICTION_FORCE: Material_Relation_Definition(
        class_name='CoulombFrictionForce',
        number=3,
        allowed_number_materials=[1, 2],
        doc_description='Shear force accounting for the tangential displacement between contacting particles.',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.FRICTION_COEFFICIENT,
                       default_value=0.0), ]
     ),
    CUDSMaterialRelation.DISSIPATION_FORCE: Material_Relation_Definition(
        class_name='DissipationForce',
        number=4,
        allowed_number_materials=[1, 2],
        doc_description='Viscous normal force describing the inelasticity of particle collisions.',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.RESTITUTION_COEFFICIENT,
                       default_value=1.0), ]
     ),
    CUDSMaterialRelation.SJKR_COHESION_FORCE: Material_Relation_Definition(
        class_name='SJKRCohesionForce',
        number=5,
        allowed_number_materials=[1, 2],
        doc_description='Additional normal force tending to maintain the contact.',  # noqa
        supported_parameters=[
             Parameter(cuba_key=CUBA.COHESION_ENERGY_DENSITY,
                       default_value=0.0), ]
     ),
}
