# code auto-generated by material_relations_generate.py
from simphony.cuds.material_relations.material_relation import (
    MaterialRelation)
from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation
from simphony.core.data_container import DataContainer


class Coulomb(MaterialRelation):

    """ A Coulomb material-relation

    Effective potential energy of the interaction between a pair of point charges.

    Attributes
    ----------
    cutoff_distance : <type 'numpy.float64'>
        Distance where force is no longer taken into account.
    dielectric_constant : <type 'numpy.float64'>
        Ratio of the permittivity of a substance to the permittivity of free space or vacuum

    """  # noqa

    def __init__(
        self,
        name,
        materials,
        description="",
        cutoff_distance=1.0,
        dielectric_constant=1.0
    ):
        super(Coulomb, self).__init__(
            name=name,
            description=description,
            kind=CUDSMaterialRelation.COULOMB,
            materials=materials,
            parameters=DataContainer({
                CUBA.CUTOFF_DISTANCE: cutoff_distance,
                CUBA.DIELECTRIC_CONSTANT: dielectric_constant,
            })
        )

    @property
    def cutoff_distance(self):
        return self._parameters[CUBA.CUTOFF_DISTANCE]

    @cutoff_distance.setter
    def cutoff_distance(self, value):
        self._parameters[CUBA.CUTOFF_DISTANCE] = value

    @property
    def dielectric_constant(self):
        return self._parameters[CUBA.DIELECTRIC_CONSTANT]

    @dielectric_constant.setter
    def dielectric_constant(self, value):
        self._parameters[CUBA.DIELECTRIC_CONSTANT] = value
