# code auto-generated by material_relations_generate.py
from simphony.cuds.material_relations.material_relation import (
    MaterialRelation)
from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation
from simphony.core.data_container import DataContainer


class FrictionForce(MaterialRelation):

    """ A FrictionForce material-relation

    Shear force accounting for the tangential displacement between contacting particles.

    Attributes
    ----------
    friction_coefficient : <type 'numpy.float64'>
        Control particle friction

    """  # noqa

    def __init__(
        self,
        name,
        materials,
        description="",
        friction_coefficient=0.0
    ):
        super(FrictionForce, self).__init__(
            name=name,
            description=description,
            kind=CUDSMaterialRelation.FRICTION_FORCE,
            materials=materials,
            parameters=DataContainer({
                CUBA.FRICTION_COEFFICIENT: friction_coefficient,
            })
        )

    @property
    def friction_coefficient(self):
        return self._parameters[CUBA.FRICTION_COEFFICIENT]

    @friction_coefficient.setter
    def friction_coefficient(self, value):
        self._parameters[CUBA.FRICTION_COEFFICIENT] = value
