# code auto-generated by material_relations_generate.py
from simphony.cuds.material_relations.material_relation import (
    MaterialRelation)
from simphony.core.cuba import CUBA
from simphony.core.cuds_material_relation import CUDSMaterialRelation
from simphony.core.data_container import DataContainer


class LennardJones(MaterialRelation):

    """ A LennardJones material-relation

    Approximated potential energy of interaction between a pair of neutral atoms or molecules based on their distance of separation.

    Attributes
    ----------
    cutoff_distance : <type 'numpy.float64'>
        Distance where force is no longer taken into account.
    energy_well_depth : <type 'numpy.float64'>
        Measurement of how strongly the two particles attract each other.
    van_der_waals_radius : <type 'numpy.float64'>
        Distance at which the intermolecular potential between the two particles is zero.

    """  # noqa

    def __init__(
        self,
        name,
        materials,
        description="",
        cutoff_distance=1.0,
        energy_well_depth=1.0,
        van_der_waals_radius=1.0
    ):
        super(LennardJones, self).__init__(
            name=name,
            description=description,
            kind=CUDSMaterialRelation.LENNARD_JONES,
            materials=materials,
            parameters=DataContainer({
                CUBA.CUTOFF_DISTANCE: cutoff_distance,
                CUBA.ENERGY_WELL_DEPTH: energy_well_depth,
                CUBA.VAN_DER_WAALS_RADIUS: van_der_waals_radius,
            })
        )

    @property
    def cutoff_distance(self):
        return self._parameters[CUBA.CUTOFF_DISTANCE]

    @cutoff_distance.setter
    def cutoff_distance(self, value):
        self._parameters[CUBA.CUTOFF_DISTANCE] = value

    @property
    def energy_well_depth(self):
        return self._parameters[CUBA.ENERGY_WELL_DEPTH]

    @energy_well_depth.setter
    def energy_well_depth(self, value):
        self._parameters[CUBA.ENERGY_WELL_DEPTH] = value

    @property
    def van_der_waals_radius(self):
        return self._parameters[CUBA.VAN_DER_WAALS_RADIUS]

    @van_der_waals_radius.setter
    def van_der_waals_radius(self, value):
        self._parameters[CUBA.VAN_DER_WAALS_RADIUS] = value
